# Install Tmux Plugin Manager at https://github.com/tmux-plugins/tpm

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'      # https://github.com/tmux-plugins/tmux-battery
set -g @plugin 'tmux-plugins/tmux-pain-control' # https://github.com/tmux-plugins/tmux-pain-control
set -g @plugin 'tmux-plugins/tmux-sidebar'      # https://github.com/tmux-plugins/tmux-sidebar
set -g @plugin 'tmux-plugins/tmux-resurrect'    # Persist tmux
set -g @plugin 'tmux-plugins/tmux-continuum'    # Persist tmux
set -g @plugin 'tmux-plugins/tmux-cpu'          # https://github.com/tmux-plugins/tmux-cpu
set -g @plugin 'jimeh/tmux-themepack'           # Theme pack

# Set theme from pack
# set -g @themepack 'basic'
set -g @themepack 'powerline/block/blue'
# set -g @themepack 'powerline/block/cyan'
# set -g @themepack 'powerline/default/gray'
# set -g @themepack 'powerline/default/green'
# set -g @themepack 'powerline/default/red' 
# set -g @themepack 'powerline/double/magenta'
# set -g @themepack 'powerline/double/yellow' 
# set -g @themepack 'powerline/block/blue' 
# set -g @themepack 'powerline/block/gray'
# set -g @themepack 'powerline/block/red'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
