" Install Pathongen 2nd: READ THIS: https://github.com/tpope/vim-pathogen
" Install NerdTree with Pathogen. READ THIS: https://github.com/scrooloose/nerdtree

" set nocompatible      " We're running Vim, not Vi!
" syntax on             " Enable syntax highlighting
set number	      " Turns on line numbers

" Basic Configuration
nnoremap <c-p> :Files<CR>
syntax enable

set encoding=utf-8

" allow copy and paste to system clipboard
set clipboard="unnamed"

" allow changing buffers w/o write
set hidden

" show line numbers
set number

" display incomplete commands
set showcmd

" Set the window title to the current file name
set title

" The number of screen lines to keep above and below the cursor.
set scrolloff=5

" The number of screen columns to keep to the left and right of the cursor.
set sidescrolloff=5

filetype plugin indent on       " load file type plugins + indentation

" Code folding configuration
"    zo opens a fold at the cursor.
"    zShift+o opens all folds at the cursor.
"    zc closes a fold at the cursor.
"    zm increases the foldlevel by one.
"    zShift+m closes all open folds.
"    zr decreases the foldlevel by one.
"    zShift+r decreases the foldlevel to zero -- all folds will be open.
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2
" end code folding configuration

"" Whitespace
set nowrap                      " don't wrap lines
" set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

""" Search Options {{{
" Enable highlighting of search results
set hlsearch

" incremental searching that shows partial matches
set incsearch

" Ignore case when searching
set ignorecase

" Automatically switch search to case-sensitive if the search string contains
" an upper-case character
set smartcase
""" }}}

" Install vim-plug if we don't already have it
if empty(glob('~/.vim/autoload/plug.vim'))
silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-rake'
Plug 'tpope/vim-markdown'
Plug 'skalnik/vim-vroom'
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim' " Nice airline + tmux stuff
Plug 'edkolev/tmuxline.vim' " Nice git things
Plug 'kchmck/vim-coffee-script' " https://github.com/leafgarland/typescript-vim
Plug 'leafgarland/typescript-vim' " Code linter, https://github.com/w0rp/ale
Plug 'w0rp/ale' " Highlight trailing whitespace
Plug 'ntpeters/vim-better-whitespace'
Plug 'noprompt/vim-yardoc'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ap/vim-css-color'
Plug 'preservim/vim-indent-guides'
Plug 'github/copilot.vim'
Plug 'kopischke/vim-fetch' " Open a file at line number file:23
call plug#end()

syntax on
filetype plugin indent on    " required
set autoindent expandtab tabstop=2 shiftwidth=2

" enable indent guides by default, :IndentGuidesDisable to disable
let g:indent_guides_enable_on_vim_startup = 1

" set indent guide colours
set background=dark

" NVM node path for Github Copilot
let g:copilot_node_command = "~/.nvm/versions/node/v19.8.1/bin/node"

" Pretties
let g:airline_theme='molokai'

execute pathogen#infect()
call pathogen#helptags()

let g:ale_fixers = {
  \   '*': ['remove_trailing_lines', 'trim_whitespace'],
  \   'javascript': ['prettier', 'eslint'],
  \   'typescript': ['prettier', 'tslint'],
  \   'ruby': ['rubocop', 'standardrb'],
  \}

let g:ale_fix_on_save = 0 " Set this to 1 if you wanna run :ALEFix on save

" Set lightline theme
let g:lightline = {
  \ 'colorscheme': 'powerline',
  \ }

