let mapleader = ","

set encoding=utf-8
set nocompatible                 " We're running Vim, not Vi!
syntax on                        " Enable syntax highlighting
set number                       " Turns on line numbers
set clipboard="unnamed"          " allow copy and paste to system clipboard
set hidden                       " allow changing buffers w/o write
set number                       " show line numbers
set showcmd                      " display incomplete commands
set title                        " Set the window title to the current file name
set relativenumber
set scrolloff=5                  " The number of screen lines to keep above and below the cursor.
set sidescrolloff=5              " The number of screen columns to keep to the left and right of the cursor.
set directory^=$HOME/.vim/swap// " set default path for VIM swp files
set nowrap                       " don't wrap lines
set expandtab                    " use spaces, not tabs (optional)
set backspace=indent,eol,start   " backspace through everything in insert mode
" set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)

filetype plugin indent on       " load file type plugins + indentation

""" fzf Options {{{
nnoremap <c-p> :Files<CR>
nnoremap <leader>G :GFiles<CR>
""" }}}

""" AndrewRadev/splitjoin.vim Options {{{
nmap <leader>sj :SplitjoinSplit<cr>
nmap <leader>sk :SplitjoinJoin<cr>
""" }}}

""" AndrewRadev/switch.vim Options {{{
nmap <leader>ss :Switch<cr>
""" }}}

""" vim-test Options {{{
nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>T :TestFile<CR>
nmap <silent> <leader>a :TestSuite<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>
let test#strategy = "asyncrun_background_term"
""" }}}

""" vim-fugitive Options {{{
" Git status
nnoremap <leader>gs :G status<CR>
" Git blame
nnoremap <leader>gb :G blame<CR>
" Git commit
nnoremap <leader>gc :G commit<CR>
" Git diff
nnoremap <leader>gd :G diff<CR>
""" }}}

""" Quicker window movement {{{
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
""" }}}

""" Folding Options {{{
"    zo opens a fold at the cursor.
"    zShift+o opens all folds at the cursor.
"    zc closes a fold at the cursor.
"    zm increases the foldlevel by one.
"    zShift+m closes all open folds.
"    zr decreases the foldlevel by one.
"    zShift+r decreases the foldlevel to zero -- all folds will be open.
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2
""" }}}


""" Search Options {{{
" Enable highlighting of search results
set hlsearch
" incremental searching that shows partial matches
set incsearch
" Ignore case when searching
set ignorecase
" ctags optimization
set autochdir
set tags=tags;
" Automatically switch search to case-sensitive if the search string contains
" an upper-case character
set smartcase
""" }}}

" Install vim-plug if we don't already have it
if empty(glob('~/.vim/autoload/plug.vim'))
silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'AndrewRadev/switch.vim'
Plug 'skywind3000/asyncrun.vim'
Plug 'junegunn/vim-easy-align'
Plug 'slim-template/vim-slim'
Plug 'vim-test/vim-test'
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-rake'
Plug 'tpope/vim-markdown'
Plug 'skalnik/vim-vroom'
Plug 'itchyny/lightline.vim'
Plug 'edkolev/tmuxline.vim'
Plug 'leafgarland/typescript-vim'
Plug 'dense-analysis/ale'
Plug 'ntpeters/vim-better-whitespace'
Plug 'noprompt/vim-yardoc'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ap/vim-css-color'
Plug 'preservim/vim-indent-guides'
Plug 'github/copilot.vim'
Plug 'kopischke/vim-fetch' " Open a file at line number file:23
call plug#end()

filetype plugin indent on    " required
set autoindent expandtab tabstop=2 shiftwidth=2

" disable indent guides by default, :IndentGuidesEnable to enable
let g:indent_guides_enable_on_vim_startup = 0

" set indent guide colours
set background=dark

" NVM node path for Github Copilot
let g:copilot_node_command = "~/.nvm/versions/node/v19.8.1/bin/node"

let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_lint_on_text_changed = 'always'
let g:ale_ruby_rubocop_executable = 'bundle'
let g:ale_ruby_standardrb_executable = 'bundle'
let g:ale_ruby_rubocop_use_bundler = 1
let g:ale_ruby_standardrb_use_bundler = 1
let g:ale_fix_on_save = 0 " Set this to 1 if you wanna run :ALEFix on save
let g:ale_fixers = {
\  '*': ['remove_trailing_lines', 'trim_whitespace'],
\  'javascript': ['prettier', 'eslint'],
\  'typescript': ['prettier', 'tslint'],
\  'ruby': ['rubocop', 'standardrb', 'rufo', 'erblint'],
\  'scss': ['prettier', 'stylelint'],
\}

" \  'ruby': ['rufo', 'standardrb', 'erblint', 'rubocop'],
" Pretties
let g:airline_theme='molokai'

" Set lightline theme
let g:lightline = {
  \ 'colorscheme': 'powerline',
  \ }

" Netrw settings
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_winsize = 20
let g:netrw_keepdir = 0

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

highlight NetrwFile       ctermfg=white
highlight NetrwDir        ctermfg=blue
highlight NetrwSymLink    ctermfg=magenta
highlight NetrwSpecial    ctermfg=yellow
highlight NetrwHelp       ctermfg=green
