# Install Tmux Plugin Manager at https://github.com/tmux-plugins/tpm

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'      # https://github.com/tmux-plugins/tmux-battery
set -g @plugin 'tmux-plugins/tmux-pain-control' # https://github.com/tmux-plugins/tmux-pain-control
set -g @plugin 'tmux-plugins/tmux-sidebar'      # https://github.com/tmux-plugins/tmux-sidebar
set -g @plugin 'tmux-plugins/tmux-resurrect'    # Persist tmux
set -g @plugin 'tmux-plugins/tmux-continuum'    # Persist tmux
set -g @plugin 'tmux-plugins/tmux-cpu'          # https://github.com/tmux-plugins/tmux-cpu
set -g @plugin 'erikw/tmux-powerline'

## Rename windows to fit current application
setw -g automatic-rename on

# Copy visual mode to clipboard like nvim
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
